### PR TITLE
Feature: Display setting values in Customizer.

### PR DESCRIPTION
**Pull request by miina**

### CODE REVIEW

**Comment by miina** [comment]
@westonruter Here is how the thumbnails currently show in Customizer:
screenshot from 2016-07-18 18 18 05

Do you think it should maybe have more actions? For example maybe we should add "X" to each image so that it would be possible to remove it directly from the Customizer without opening Media Modal?

**Comment by westonruter** [comment]
@miina good idea, but I'd say that might be an enhancement. I could see where drag-and-drop reordering and an X to delete individual gallery items would both be handy, but I think these are less important than getting a quick overview of the contents of the gallery.

Also, I think the gallery images should be displayed much smaller, more as icons rather than full thumbnails.

**Comment by miina** [comment]
@westonruter Changed the image sizes to smaller, here is how it is now:
screenshot from 2016-07-19 14 34 08

Could you please check the PR if it's OK to merge?

**Comment by westonruter** [comment]
@miina that looks _great_!

**Pull request merged**
